use std::collections::{HashMap, HashSet};
use std::time::Instant;

use serde_json::{json, Value};
use tokio::io::DuplexStream;

use super::sse::SseEvent;
use super::stream_helpers::{
    apply_common_params, build_done_event, build_start_event, build_tool_use_event,
    extract_anthropic_usage, extract_system_text, merge_anthropic_usage,
};
use crate::types::{ContentBlock, GenerateResponse, LlmRequest, Timing, Usage};
use crate::LlmError;

const DEFAULT_BASE_URL: &str = "https://api.anthropic.com";
const ANTHROPIC_VERSION: &str = "2023-06-01";

/// Effort values that map to adaptive thinking + output_config on Anthropic.
const ANTHROPIC_EFFORT_VALUES: &[&str] = &["max", "xhigh", "high", "medium", "low"];

fn is_effort_value(s: &str) -> bool {
    ANTHROPIC_EFFORT_VALUES.contains(&s)
}

// ── Helpers ──────────────────────────────────────────────────────────────

/// Returns true if `msg` is a user message whose content is an array where
/// every block has `"type": "tool_result"`.
fn is_tool_result_message(msg: &Value) -> bool {
    if msg.get("role").and_then(Value::as_str) != Some("user") {
        return false;
    }
    let Some(arr) = msg.get("content").and_then(Value::as_array) else {
        return false;
    };
    !arr.is_empty()
        && arr
            .iter()
            .all(|b| b.get("type").and_then(Value::as_str) == Some("tool_result"))
}

/// Strip all `cache_control` keys from every content block in `messages`.
fn strip_cache_control(messages: &mut [Value]) {
    for msg in messages.iter_mut() {
        let Some(arr) = msg.get_mut("content").and_then(Value::as_array_mut) else {
            continue;
        };
        for block in arr.iter_mut() {
            if let Some(obj) = block.as_object_mut() {
                obj.remove("cache_control");
            }
        }
    }
}

/// Check whether any message already has cache_control markers on its content
/// blocks. Provider-normalized requests should usually arrive unmarked; this
/// guard avoids stacking duplicate markers if a caller supplies annotated
/// messages explicitly.
fn messages_have_cache_control(messages: &[Value]) -> bool {
    messages.iter().any(|m| {
        m.get("content")
            .and_then(Value::as_array)
            .is_some_and(|arr| arr.iter().any(|b| b.get("cache_control").is_some()))
    })
}

/// Find the turn-boundary position for a cache breakpoint.
///
/// A "turn" is a real user message plus everything through the final
/// assistant response (including any tool-use exchanges).  `depth` counts
/// in turns, not messages.  The breakpoint lands on the last message of the
/// turn that is `depth` turns before the current one — always at a stable
/// turn boundary regardless of how many tool exchanges occurred within each
/// turn.
fn find_turn_boundary(messages: &[Value], depth: usize) -> Option<usize> {
    if messages.is_empty() {
        return None;
    }

    let current_user_idx = messages.iter().rposition(|m| {
        m.get("role").and_then(Value::as_str) == Some("user") && !is_tool_result_message(m)
    });

    let mut real_user_count = 0;
    let mut best: Option<usize> = None;
    for i in (0..messages.len()).rev() {
        if messages[i].get("role").and_then(Value::as_str) == Some("user")
            && !is_tool_result_message(&messages[i])
        {
            real_user_count += 1;
            if real_user_count == depth + 1 && i > 0 {
                // Ideal: exact depth reached.
                return Some(i - 1);
            }
            if real_user_count == depth + 1 {
                // Exact target is the first message. Cache it only when it is
                // historical; never place a message breakpoint on the active
                // user message itself.
                return if Some(i) == current_user_idx && i + 1 == messages.len() {
                    None
                } else {
                    Some(0)
                };
            }
            // Track the earliest real user message as fallback.
            best = Some(i);
        }
    }
    // Fallback: not enough turns for requested depth — place breakpoint on
    // the first message (index 0) so we still get *some* caching rather
    // than wasting the entire prefix.
    if best.is_some()
        && !(best == current_user_idx && current_user_idx == Some(messages.len().saturating_sub(1)))
    {
        Some(0)
    } else {
        None
    }
}

/// Find a completed tool-loop boundary for a cache breakpoint.
///
/// Tool-result messages are generated by Shore after an assistant tool-use
/// response and are stable by the time the next API request is made. Treating
/// them as cacheable sub-turn boundaries prevents long tool loops from paying
/// the entire accumulated tool transcript as fresh input on every iteration.
fn find_tool_result_boundary(messages: &[Value], depth: usize) -> Option<usize> {
    messages
        .iter()
        .enumerate()
        .rev()
        .filter_map(|(idx, msg)| is_tool_result_message(msg).then_some(idx))
        .nth(depth)
}

/// Build a cache_control value, including TTL if non-default.
fn make_cache_control(cache_ttl: &str) -> Value {
    let mut cc = json!({ "type": "ephemeral" });
    if !cache_ttl.is_empty() && cache_ttl != "5m" {
        cc["ttl"] = json!(cache_ttl);
    }
    cc
}

/// Apply cache_control breakpoint to the last text block of a message.
fn apply_breakpoint_to_message(msg: &mut Value, cc: &Value) {
    let content = msg.get("content").cloned();
    match content {
        Some(Value::String(text)) => {
            msg["content"] = json!([{
                "type": "text",
                "text": text,
                "cache_control": cc,
            }]);
        }
        Some(Value::Array(_)) => {
            if let Some(arr) = msg.get_mut("content").and_then(Value::as_array_mut) {
                // Find last text block and apply cache_control.
                for block in arr.iter_mut().rev() {
                    if let Some(obj) = block.as_object_mut() {
                        let btype = obj.get("type").and_then(Value::as_str).unwrap_or("");
                        if btype == "text" || btype == "tool_result" {
                            obj.insert("cache_control".into(), cc.clone());
                            break;
                        }
                    }
                }
            }
        }
        _ => {}
    }
}

/// Info returned alongside the cache-annotated payload for forensics.
struct CachePlacement {
    /// Message breakpoint positions (sorted).
    msg_breakpoints: Vec<usize>,
    /// System block breakpoint positions (sorted).
    sys_breakpoints: Vec<usize>,
    sys_blocks: usize,
    prefix_hash: u64,
}

/// Parse a comma-separated env var into a Vec of integers.
fn parse_env_vec<T: std::str::FromStr>(var: &str) -> Option<Vec<T>> {
    std::env::var(var).ok().map(|s| {
        s.split(',')
            .filter_map(|v| v.trim().parse::<T>().ok())
            .collect()
    })
}

/// Resolve `cache_depth_turns` values into concrete message indices.
///
/// Each depth value N means "N user turns back from the end". The breakpoint
/// is placed on the last message of the turn *before* the Nth-from-end user
/// turn, so that editing the Nth-from-end message doesn't bust the cache.
fn resolve_depth_turns(messages: &[Value], depths: &[u32]) -> Vec<usize> {
    let mut positions = Vec::new();
    let in_tool_loop = messages.last().is_some_and(is_tool_result_message);
    for &depth in depths {
        let pos = if in_tool_loop {
            find_tool_result_boundary(messages, depth as usize)
                .or_else(|| find_turn_boundary(messages, depth as usize))
        } else {
            find_turn_boundary(messages, depth as usize)
        };
        if let Some(pos) = pos {
            positions.push(pos);
        }
    }
    positions
}

/// Resolve `cache_pinned_position` values into system or message breakpoints.
///
/// - `0`: breakpoint on the last system block (between system and messages).
/// - Negative: index from end of system blocks (-1 = second-to-last, etc.).
/// - Positive: pinned at the Nth user turn in messages.
fn resolve_pinned_positions(
    messages: &[Value],
    system_len: usize,
    positions: &[i32],
) -> (Vec<usize>, Vec<usize>) {
    let mut sys_indices = Vec::new();
    let mut msg_indices = Vec::new();
    for &pos in positions {
        if pos <= 0 {
            // System block breakpoint.
            // 0 = last block, -1 = second-to-last, etc.
            let idx = system_len as i32 - 1 + pos; // 0→last, -1→second-to-last
            if idx >= 0 && (idx as usize) < system_len {
                sys_indices.push(idx as usize);
            }
        } else {
            // Positive: pin at Nth user turn.
            // Find the message index of the Nth real user turn.
            let mut user_count = 0u32;
            for (i, msg) in messages.iter().enumerate() {
                if msg.get("role").and_then(Value::as_str) == Some("user")
                    && !is_tool_result_message(msg)
                {
                    user_count += 1;
                    if user_count == pos as u32 {
                        // Breakpoint on the message after this user turn's
                        // assistant response (or the user message itself if
                        // there's no assistant response yet).
                        let bp = if i + 1 < messages.len() { i + 1 } else { i };
                        msg_indices.push(bp);
                        break;
                    }
                }
            }
        }
    }
    (sys_indices, msg_indices)
}

/// Apply cache_control breakpoints to messages and system.
///
/// Breakpoints are configured via two arrays in provider_options:
/// - `cache_depth_turns`: sliding breakpoints relative to conversation end
/// - `cache_pinned_position`: static breakpoints at fixed positions
///
/// Both are overridable via `SHORE_CACHE_DEPTH_TURNS` and
/// `SHORE_CACHE_PINNED_POSITION` environment variables (comma-separated).
///
/// Combined total must not exceed 4 (Anthropic's limit).
fn apply_cache_control(
    messages: &[Value],
    system: &Value,
    cache_ttl: &str,
    depth_turns: &[u32],
    pinned_positions: &[i32],
) -> (Vec<Value>, Value, CachePlacement) {
    // Normalize string system prompt to array-of-blocks so cache_control
    // markers can be attached.
    let system = if let Some(s) = system.as_str() {
        json!([{ "type": "text", "text": s }])
    } else {
        system.clone()
    };

    let sys_blocks = system.as_array().map(|a| a.len()).unwrap_or(0);

    if messages.is_empty() {
        return (
            messages.to_vec(),
            system,
            CachePlacement {
                msg_breakpoints: vec![],
                sys_breakpoints: vec![],
                sys_blocks,
                prefix_hash: 0,
            },
        );
    }

    let mut result: Vec<Value> = messages.to_vec();

    // Step 1: Strip all existing cache_control from all content blocks.
    strip_cache_control(&mut result);

    // Step 2: Normalize all plain-string content to array format so the
    // serialised payload structure is identical regardless of where the
    // cache breakpoint lands.
    for msg in result.iter_mut() {
        if let Some(Value::String(text)) = msg.get("content").cloned() {
            msg["content"] = json!([{ "type": "text", "text": text }]);
        }
    }

    // Step 3: Env var overrides.
    let depth_turns =
        parse_env_vec::<u32>("SHORE_CACHE_DEPTH_TURNS").unwrap_or_else(|| depth_turns.to_vec());
    let pinned_positions = parse_env_vec::<i32>("SHORE_CACHE_PINNED_POSITION")
        .unwrap_or_else(|| pinned_positions.to_vec());

    // Step 4: Resolve breakpoint positions.
    let depth_msg_indices = resolve_depth_turns(&result, &depth_turns);
    let (pinned_sys_indices, pinned_msg_indices) =
        resolve_pinned_positions(&result, sys_blocks, &pinned_positions);

    // Deduplicate and sort message breakpoints.
    let mut msg_bp: Vec<usize> = depth_msg_indices
        .into_iter()
        .chain(pinned_msg_indices)
        .collect();
    msg_bp.sort_unstable();
    msg_bp.dedup();

    // Deduplicate system breakpoints.
    let mut sys_bp: Vec<usize> = pinned_sys_indices;
    sys_bp.sort_unstable();
    sys_bp.dedup();

    // Enforce Anthropic's 4-breakpoint limit.
    let total = msg_bp.len() + sys_bp.len();
    if total > 4 {
        tracing::warn!(
            total,
            msg = msg_bp.len(),
            sys = sys_bp.len(),
            "apply_cache_control: too many breakpoints ({total}), truncating to 4"
        );
        // Keep system breakpoints, truncate message breakpoints.
        let allowed_msg = 4usize.saturating_sub(sys_bp.len());
        msg_bp.truncate(allowed_msg);
    }

    // Step 5: Apply breakpoints.
    let cc = make_cache_control(cache_ttl);

    // System breakpoints.
    let mut sys = system;
    if let Some(arr) = sys.as_array_mut() {
        for &idx in &sys_bp {
            if let Some(obj) = arr.get_mut(idx).and_then(Value::as_object_mut) {
                obj.insert("cache_control".into(), cc.clone());
                tracing::debug!(idx, "apply_cache_control: system breakpoint placed");
            }
        }
        // Strip _label fields — internal metadata, not part of the API.
        for block in arr.iter_mut() {
            if let Some(obj) = block.as_object_mut() {
                obj.remove("_label");
            }
        }
    }

    // Message breakpoints.
    for &pos in &msg_bp {
        if pos < result.len() {
            apply_breakpoint_to_message(&mut result[pos], &cc);
            tracing::debug!(pos, "apply_cache_control: message breakpoint placed");
        }
    }

    // Step 6: Compute prefix hash for forensics.
    let prefix_hash = {
        use std::hash::{Hash, Hasher};
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        sys.to_string().hash(&mut hasher);
        // Hash messages up to and including the earliest message breakpoint.
        let end = msg_bp.first().map(|&p| p + 1).unwrap_or(0);
        for msg in &result[..end] {
            msg.to_string().hash(&mut hasher);
        }
        hasher.finish()
    };

    tracing::debug!(
        total_messages = result.len(),
        msg_breakpoints = ?msg_bp,
        sys_breakpoints = ?sys_bp,
        prefix_hash = format!("{prefix_hash:016x}"),
        "apply_cache_control: breakpoint placement"
    );

    (
        result,
        sys,
        CachePlacement {
            msg_breakpoints: msg_bp,
            sys_breakpoints: sys_bp,
            sys_blocks,
            prefix_hash,
        },
    )
}

/// Build the `thinking` config param from provider_options.
fn build_thinking_config(opts: &Value) -> Option<Value> {
    let effort = opts.get("reasoning_effort").and_then(Value::as_str);

    // "adaptive" or named effort values → adaptive thinking mode.
    if effort == Some("adaptive") || effort.is_some_and(is_effort_value) {
        return Some(json!({ "type": "adaptive" }));
    }

    // Explicit budget: enable thinking with the given token budget.
    let thinking_flag = opts
        .get("thinking")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let budget = opts.get("budget_tokens").and_then(Value::as_u64);

    if thinking_flag || budget.is_some() {
        return Some(json!({
            "type": "enabled",
            "budget_tokens": budget.unwrap_or(1024)
        }));
    }

    None
}

/// Build `output_config` for named effort levels.
fn build_output_config(opts: &Value) -> Option<Value> {
    let effort = opts.get("reasoning_effort").and_then(Value::as_str)?;
    if is_effort_value(effort) {
        Some(json!({ "effort": effort }))
    } else {
        None
    }
}

/// Extract plain text from a message's content (string or array of blocks).
fn extract_text_content(msg: &Value) -> String {
    extract_system_text(msg.get("content").unwrap_or(&Value::Null))
}

/// Convert inline system-role messages to user messages.
///
/// The Anthropic API does not support `role: "system"` in the messages array,
/// so we wrap the instruction in `<system_instruction>` XML tags and emit it
/// as a user message.  When the preceding message is already a user turn,
/// the instruction is merged into it to avoid consecutive user roles.
fn convert_inline_system_messages(messages: &[Value]) -> Vec<Value> {
    let has_system = messages
        .iter()
        .any(|m| m.get("role").and_then(Value::as_str) == Some("system"));
    if !has_system {
        return messages.to_vec();
    }

    let mut out: Vec<Value> = Vec::with_capacity(messages.len());
    for msg in messages {
        if msg.get("role").and_then(Value::as_str) == Some("system") {
            let text = extract_text_content(msg);
            let wrapped = super::stream_helpers::wrap_inline_system_instruction(&text);

            // If the previous message is a user message, merge to avoid
            // consecutive user roles (which the API rejects). Preserve
            // structured content (tool_result, image blocks, etc.) by
            // appending a text block rather than stringifying — otherwise
            // extract_text_content would silently drop non-text blocks and
            // break tool_use/tool_result pairing.
            if let Some(prev) = out.last_mut() {
                if prev.get("role").and_then(Value::as_str) == Some("user") {
                    match prev.get_mut("content") {
                        Some(Value::Array(blocks)) => {
                            blocks.push(json!({"type": "text", "text": wrapped}));
                        }
                        _ => {
                            let prev_text = extract_text_content(prev);
                            prev["content"] = json!(format!("{prev_text}\n\n{wrapped}"));
                        }
                    }
                    continue;
                }
            }

            out.push(json!({ "role": "user", "content": wrapped }));
        } else {
            out.push(msg.clone());
        }
    }
    out
}

/// Construct the JSON request body for the Anthropic Messages API.
///
/// Returns `(body, call_id)` where `call_id` is a forensic correlation ID
/// (0 when forensics is disabled).
fn build_body(request: &LlmRequest, streaming: bool) -> (Value, u64) {
    let opts = request.provider_options.as_ref();
    let empty_opts = json!({});
    let opts_ref = opts.unwrap_or(&empty_opts);

    // Convert inline system-role messages to user/assistant pairs before
    // any further processing (Anthropic rejects role: "system" in messages).
    let converted_messages = convert_inline_system_messages(&request.messages);

    // Cache is enabled when cache_ttl is present and non-empty.
    let cache_ttl = opts_ref
        .get("cache_ttl")
        .and_then(Value::as_str)
        .unwrap_or("");
    let cache_enabled = !cache_ttl.is_empty();
    let has_existing_markers = messages_have_cache_control(&converted_messages);

    let msg_count = converted_messages.len();

    // Cache breakpoint defaults: depth=[0,1] (two sliding message breakpoints)
    // and pinned=[-1] (system anchor on second-to-last block). The last
    // system block is the `<memory_index>` rendering of MEMORY.md, which can
    // change at every compaction; placing the anchor one block above it keeps
    // the cached prefix stable when the index is rewritten.
    //
    // Sliding breakpoints WITHOUT a system anchor are unreliable (intermittent
    // full prefix rewrites despite identical content). See ARCHITECTURE.md.
    //
    // Overridable via SHORE_CACHE_DEPTH_TURNS and SHORE_CACHE_PINNED_POSITION
    // env vars (comma-separated) for debugging.
    let depth_turns: Vec<u32> = vec![0, 1];
    let pinned_positions: Vec<i32> = vec![-1];

    let (messages, system, placement) = if cache_enabled && !has_existing_markers {
        apply_cache_control(
            &converted_messages,
            request.system.as_ref().unwrap_or(&json!(null)),
            cache_ttl,
            &depth_turns,
            &pinned_positions,
        )
    } else {
        (
            converted_messages,
            request.system.clone().unwrap_or(json!(null)),
            CachePlacement {
                msg_breakpoints: vec![],
                sys_breakpoints: vec![],
                sys_blocks: 0,
                prefix_hash: 0,
            },
        )
    };

    // -- Cache forensics: log every Anthropic request --
    let call_id = if crate::cache_forensics::is_enabled() {
        let id = crate::cache_forensics::next_call_id();
        crate::cache_forensics::log_request(crate::cache_forensics::RequestLog {
            call_id: id,
            character: request.forensic_character.as_deref(),
            model: &request.model,
            msg_count,
            msg_breakpoints: &placement.msg_breakpoints,
            sys_breakpoints: &placement.sys_breakpoints,
            sys_blocks: placement.sys_blocks,
            prefix_hash: placement.prefix_hash,
            has_existing_markers,
            cache_enabled,
            rid: request.rid.as_deref(),
        });
        id
    } else {
        0
    };

    let thinking = build_thinking_config(opts_ref);
    let output_config = build_output_config(opts_ref);

    let mut body = json!({
        "model": request.model,
        "max_tokens": request.max_tokens,
        "messages": messages,
    });

    if streaming {
        body["stream"] = json!(true);
    }

    // Use the (possibly cache-annotated) system value.
    if !system.is_null() {
        body["system"] = system;
    }

    if let Some(ref tools) = request.tools {
        if !tools.is_empty() {
            body["tools"] = json!(tools);
        }
    }

    apply_common_params(&mut body, request);

    if let Some(thinking) = thinking {
        body["thinking"] = thinking;
    }

    if let Some(output_config) = output_config {
        body["output_config"] = output_config;
    }

    // OpenRouter provider routing (e.g. force google-vertex).
    if let Some(or_provider) = opts_ref.get("openrouter_provider") {
        let mut provider = or_provider.clone();
        if let Some(obj) = provider.as_object_mut() {
            if obj.contains_key("order") {
                obj.entry("allow_fallbacks".to_string())
                    .or_insert(json!(false));
            }
        }
        body["provider"] = provider;
    }

    (body, call_id)
}

/// Build the reqwest request with Anthropic-specific headers.
///
/// Accepts any `base_url`, enabling the Anthropic wire protocol through
/// third-party gateways (e.g. OpenRouter, Bedrock proxies).
/// Returns `(request_builder, forensic_call_id)`.
fn build_http_request(
    client: &reqwest::Client,
    request: &LlmRequest,
    streaming: bool,
) -> Result<(reqwest::RequestBuilder, u64), LlmError> {
    let base = request.base_url.as_deref().unwrap_or(DEFAULT_BASE_URL);
    // If the base_url already includes a version path (e.g. OpenRouter's
    // default "https://openrouter.ai/api/v1"), just append /messages.
    let url = if base.ends_with("/v1") {
        format!("{base}/messages")
    } else {
        format!("{base}/v1/messages")
    };
    let (body, call_id) = build_body(request, streaming);

    // Dump the full transformed body to a per-call file for debugging.
    if crate::cache_forensics::is_enabled() {
        let dump_dir = std::path::Path::new("/tmp/shore-body-dumps");
        let _ = std::fs::create_dir_all(dump_dir);
        let path = dump_dir.join(format!("call_{call_id}.json"));
        let _ = std::fs::write(
            &path,
            serde_json::to_string_pretty(&body).unwrap_or_default(),
        );
    }

    // Log the post-transformation payload shape (no message content).
    {
        let model = body["model"].as_str().unwrap_or("?");
        let max_tokens = body["max_tokens"].as_u64().unwrap_or(0);
        let thinking = body
            .get("thinking")
            .map(|v| v.to_string())
            .unwrap_or_else(|| "none".into());
        let output_cfg = body
            .get("output_config")
            .map(|v| v.to_string())
            .unwrap_or_else(|| "none".into());
        let sys_blocks = body["system"].as_array().map(|a| a.len()).unwrap_or(0);
        let msg_count = body["messages"].as_array().map(|a| a.len()).unwrap_or(0);
        let tool_count = body
            .get("tools")
            .and_then(|v| v.as_array())
            .map(|a| a.len())
            .unwrap_or(0);
        tracing::debug!(
            model, max_tokens, %thinking, output_config = %output_cfg,
            sys_blocks, msg_count, tool_count,
            "Anthropic: transformed request body"
        );
    }

    let mut builder = client
        .post(&url)
        .header("anthropic-version", ANTHROPIC_VERSION)
        .header("content-type", "application/json")
        .header("x-api-key", &request.api_key);

    if let Some(ref rid) = request.rid {
        builder = builder.header("X-Request-ID", rid);
    }

    Ok((builder.json(&body), call_id))
}

use super::check_response;

// ── Streaming ────────────────────────────────────────────────────────────

/// State tracked across SSE events during stream translation.
struct StreamState {
    /// Accumulated text content (concatenation of all text_delta texts).
    text_content: String,
    /// Finish reason from message_delta.
    finish_reason: String,
    /// Token usage (input from message_start, output from message_delta).
    usage: Usage,
    /// Model name from message_start.
    model: String,
    /// Start time for timing calculation.
    start_time: Instant,
    /// Time to first token.
    first_token_time: Option<Instant>,

    // Track active tool_use blocks by index.
    tool_blocks: HashMap<u64, ToolBlockState>,
    // Track thinking block indices.
    thinking_blocks: HashSet<u64>,
    // Track accumulated signatures for thinking blocks.
    thinking_signatures: HashMap<u64, String>,
    // Track redacted_thinking blocks (arrive complete at content_block_start).
    redacted_thinking_blocks: HashMap<u64, String>,
}

struct ToolBlockState {
    id: String,
    name: String,
    json_chunks: Vec<String>,
}

impl StreamState {
    fn new(model: &str) -> Self {
        Self {
            text_content: String::new(),
            finish_reason: "end_turn".into(),
            usage: Usage::default(),
            model: model.to_string(),
            start_time: Instant::now(),
            first_token_time: None,
            tool_blocks: HashMap::new(),
            thinking_blocks: HashSet::new(),
            thinking_signatures: HashMap::new(),
            redacted_thinking_blocks: HashMap::new(),
        }
    }
}

/// Send a streaming request to the Anthropic Messages API.
///
/// Returns the read half of a `DuplexStream` that yields NDJSON `StreamEvent`
/// lines. A background task reads SSE events from the HTTP response and
/// translates them into the normalized stream format.
pub async fn stream(
    client: &reqwest::Client,
    request: &LlmRequest,
) -> Result<DuplexStream, LlmError> {
    let (http_req, _call_id) = build_http_request(client, request, true)?;
    let response = http_req.send().await.map_err(|e| LlmError::Provider {
        message: format!("HTTP request failed: {e}"),
    })?;
    let response = check_response(response).await?;

    let (read_half, mut write_half) = tokio::io::duplex(64 * 1024);

    let model = request.model.clone();
    tokio::spawn(async move {
        let mut state = StreamState::new(&model);

        let result = super::sse::read_sse_events(
            response,
            |event| handle_sse_event(event, &mut state),
            &mut write_half,
        )
        .await;

        if let Err(e) = result {
            tracing::warn!(error = %e, "SSE stream error in Anthropic provider");
        }
        // Drop write_half so the reader sees EOF.
    });

    Ok(read_half)
}

/// Translate an SSE event into an optional NDJSON line to write to the stream.
fn handle_sse_event(event: SseEvent, state: &mut StreamState) -> Option<String> {
    // Prefer the SSE `event:` field; fall back to the `type` field inside the
    // JSON `data:` payload.  Some proxies (e.g. OpenRouter) may strip the
    // `event:` line and only forward `data:`.
    let event_type_owned: Option<String> = event.event.clone().or_else(|| {
        serde_json::from_str::<serde_json::Value>(&event.data)
            .ok()
            .and_then(|v| v.get("type").and_then(|t| t.as_str()).map(String::from))
    });
    let event_type = event_type_owned.as_deref().unwrap_or("");

    match event_type {
        "message_start" => handle_message_start(&event.data, state),
        "content_block_start" => handle_content_block_start(&event.data, state),
        "content_block_delta" => handle_content_block_delta(&event.data, state),
        "content_block_stop" => handle_content_block_stop(&event.data, state),
        "message_delta" => {
            handle_message_delta(&event.data, state);
            None
        }
        "message_stop" => Some(handle_message_stop(state)),
        "ping" => None,
        other => {
            if !other.is_empty() {
                tracing::debug!(event_type = other, "Unknown Anthropic SSE event type");
            }
            None
        }
    }
}

fn handle_message_start(data: &str, state: &mut StreamState) -> Option<String> {
    let parsed: Value = serde_json::from_str(data).ok()?;
    let message = parsed.get("message")?;

    if let Some(model) = message.get("model").and_then(Value::as_str) {
        state.model = model.to_string();
    }

    if let Some(usage) = message.get("usage") {
        merge_anthropic_usage(&mut state.usage, usage);
    }

    Some(build_start_event(&state.model))
}

fn handle_content_block_start(data: &str, state: &mut StreamState) -> Option<String> {
    let parsed: Value = serde_json::from_str(data).ok()?;
    let index = parsed.get("index").and_then(Value::as_u64)?;
    let block = parsed.get("content_block")?;
    let block_type = block.get("type").and_then(Value::as_str)?;

    match block_type {
        "tool_use" => {
            let id = block
                .get("id")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            let name = block
                .get("name")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            state.tool_blocks.insert(
                index,
                ToolBlockState {
                    id,
                    name,
                    json_chunks: Vec::new(),
                },
            );
            None
        }
        "thinking" => {
            state.thinking_blocks.insert(index);
            None
        }
        "redacted_thinking" => {
            let data_str = block
                .get("data")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            // OpenRouter injects bogus redacted_thinking blocks that duplicate
            // real thinking content. Filter them at the source.
            if data_str.starts_with("openrouter.reasoning:") {
                tracing::debug!("Filtered OpenRouter redacted_thinking wrapper");
                return None;
            }
            state.redacted_thinking_blocks.insert(index, data_str);
            None
        }
        _ => None,
    }
}

fn handle_content_block_delta(data: &str, state: &mut StreamState) -> Option<String> {
    let parsed: Value = serde_json::from_str(data).ok()?;
    let index = parsed.get("index").and_then(Value::as_u64)?;
    let delta = parsed.get("delta")?;
    let delta_type = delta.get("type").and_then(Value::as_str)?;

    match delta_type {
        "text_delta" => {
            if state.first_token_time.is_none() {
                state.first_token_time = Some(Instant::now());
            }
            let text = delta.get("text").and_then(Value::as_str).unwrap_or("");
            state.text_content.push_str(text);
            Some(json!({ "type": "text", "text": text }).to_string())
        }
        "thinking_delta" => {
            if state.first_token_time.is_none() {
                state.first_token_time = Some(Instant::now());
            }
            let thinking = delta.get("thinking").and_then(Value::as_str).unwrap_or("");
            Some(json!({ "type": "thinking", "text": thinking }).to_string())
        }
        "signature_delta" => {
            if state.thinking_blocks.contains(&index) {
                let sig = delta.get("signature").and_then(Value::as_str).unwrap_or("");
                state
                    .thinking_signatures
                    .entry(index)
                    .or_default()
                    .push_str(sig);
            }
            None
        }
        "input_json_delta" => {
            if let Some(tool) = state.tool_blocks.get_mut(&index) {
                let partial = delta
                    .get("partial_json")
                    .and_then(Value::as_str)
                    .unwrap_or("");
                tool.json_chunks.push(partial.to_string());
            }
            None
        }
        _ => None,
    }
}

fn handle_content_block_stop(data: &str, state: &mut StreamState) -> Option<String> {
    let parsed: Value = serde_json::from_str(data).ok()?;
    let index = parsed.get("index").and_then(Value::as_u64)?;

    // Collect all lines to emit — we may have up to 2 (tool_use + thinking_sig,
    // or redacted_thinking + thinking_sig, etc.). We return only the first one
    // from this callback; for simplicity, since the SSE parser writes one line
    // per callback return, we combine multiple events into one if needed.
    // Actually, the callback can only return one line. We need to handle the
    // case where content_block_stop can emit multiple events. Looking at the TS,
    // it checks tool_use, then thinking, then redacted_thinking — these are
    // mutually exclusive block types, so we'll only ever emit one line per stop.

    // Check for tool_use block completion.
    if let Some(tool) = state.tool_blocks.remove(&index) {
        let raw = tool.json_chunks.join("");
        let input: Value = if raw.is_empty() {
            json!({})
        } else {
            serde_json::from_str(&raw).unwrap_or(json!({}))
        };
        return Some(build_tool_use_event(&tool.id, &tool.name, &input));
    }

    // Check for thinking block completion — emit accumulated signature.
    if state.thinking_blocks.remove(&index) {
        if let Some(sig) = state.thinking_signatures.remove(&index) {
            return Some(json!({ "type": "thinking_signature", "signature": sig }).to_string());
        }
        return None;
    }

    // Check for redacted_thinking block completion.
    if let Some(redacted_data) = state.redacted_thinking_blocks.remove(&index) {
        return Some(json!({ "type": "redacted_thinking", "data": redacted_data }).to_string());
    }

    None
}

fn handle_message_delta(data: &str, state: &mut StreamState) {
    let Ok(parsed) = serde_json::from_str::<Value>(data) else {
        return;
    };

    if let Some(delta) = parsed.get("delta") {
        if let Some(reason) = delta.get("stop_reason").and_then(Value::as_str) {
            state.finish_reason = reason.to_string();
        }
    }

    if let Some(usage) = parsed.get("usage") {
        merge_anthropic_usage(&mut state.usage, usage);
    }
}

fn handle_message_stop(state: &mut StreamState) -> String {
    let total_ms = state.start_time.elapsed().as_millis() as u32;
    let ttft_ms = state
        .first_token_time
        .map(|t| t.duration_since(state.start_time).as_millis() as u32)
        .unwrap_or(total_ms);
    build_done_event(
        &state.text_content,
        &state.finish_reason,
        &state.usage,
        total_ms,
        ttft_ms,
    )
}

// ── Non-streaming ────────────────────────────────────────────────────────

/// Send a non-streaming generate request to the Anthropic Messages API.
pub async fn generate(
    client: &reqwest::Client,
    request: &LlmRequest,
) -> Result<GenerateResponse, LlmError> {
    let start = Instant::now();
    let (http_req, call_id) = build_http_request(client, request, false)?;
    let response = http_req.send().await.map_err(|e| LlmError::Provider {
        message: format!("HTTP request failed: {e}"),
    })?;
    let response = check_response(response).await?;

    let body: Value = response.json().await.map_err(|e| LlmError::Provider {
        message: format!("failed to read response body: {e}"),
    })?;

    let total_ms = start.elapsed().as_millis() as u32;

    // Extract model.
    let model = body
        .get("model")
        .and_then(Value::as_str)
        .unwrap_or(&request.model)
        .to_string();

    // Extract finish reason.
    let finish_reason = body
        .get("stop_reason")
        .and_then(Value::as_str)
        .unwrap_or("end_turn")
        .to_string();

    // Extract usage.
    let usage = extract_anthropic_usage(body.get("usage"));

    // Extract content blocks.
    let raw_blocks = body.get("content").and_then(Value::as_array);

    let mut text_content = String::new();
    let mut content_blocks = Vec::new();

    if let Some(blocks) = raw_blocks {
        for block in blocks {
            let block_type = block.get("type").and_then(Value::as_str).unwrap_or("");
            match block_type {
                "text" => {
                    let text = block.get("text").and_then(Value::as_str).unwrap_or("");
                    text_content.push_str(text);
                    content_blocks.push(ContentBlock::Text {
                        text: text.to_string(),
                    });
                }
                "thinking" => {
                    let thinking = block
                        .get("thinking")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string();
                    let signature = block
                        .get("signature")
                        .and_then(Value::as_str)
                        .map(String::from);
                    content_blocks.push(ContentBlock::Thinking {
                        thinking,
                        signature,
                    });
                }
                "redacted_thinking" => {
                    let data = block
                        .get("data")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string();
                    if !data.starts_with("openrouter.reasoning:") {
                        content_blocks.push(ContentBlock::RedactedThinking { data });
                    }
                }
                "tool_use" => {
                    let id = block
                        .get("id")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string();
                    let name = block
                        .get("name")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_string();
                    let input = block.get("input").cloned().unwrap_or(json!({}));
                    content_blocks.push(ContentBlock::ToolUse { id, name, input });
                }
                _ => {}
            }
        }
    }

    let timing = Timing {
        total_ms,
        time_to_first_token_ms: total_ms,
    };

    // Forensic log: response side (non-streaming only — streaming is
    // logged from the ledger's record_call since usage arrives later).
    if call_id > 0 && (usage.cache_creation_tokens > 0 || usage.cache_read_tokens > 0) {
        crate::cache_forensics::log_response(crate::cache_forensics::ResponseLog {
            call_id,
            model: &model,
            character: "", // character not known at this layer
            call_type: "", // call_type not known at this layer
            input_tokens: usage.input_tokens,
            output_tokens: usage.output_tokens,
            cache_read_tokens: usage.cache_read_tokens,
            cache_creation_tokens: usage.cache_creation_tokens,
        });
    }

    Ok(GenerateResponse {
        content: text_content,
        content_blocks,
        finish_reason,
        usage,
        timing,
        model,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use shore_config::models::Sdk;

    fn make_request(messages: Vec<Value>, system: Option<Value>) -> LlmRequest {
        LlmRequest {
            sdk: Sdk::Anthropic,
            model: "claude-test".into(),
            api_key: "sk-test".into(),
            api_key_name: None,
            base_url: None,
            messages,
            system,
            tools: None,
            max_tokens: 4096,
            temperature: None,
            top_p: None,
            provider_options: None,
            provider_key: None,
            rid: None,
            forensic_character: None,
            system_suffix: None,
            retain_long: false,
        }
    }

    // ── apply_cache_control ────────────────────────────────────────────

    #[test]
    fn test_apply_cache_control_empty_messages() {
        let (msgs, sys, p) = apply_cache_control(&[], &json!(null), "5m", &[], &[]);
        assert!(msgs.is_empty());
        assert_eq!(sys, json!(null));
        assert!(p.msg_breakpoints.is_empty());
        assert!(p.sys_breakpoints.is_empty());
    }

    #[test]
    fn test_apply_cache_control_pinned_system_last_block() {
        // cache_pinned_position = [0] → breakpoint on last system block.
        let system = json!([
            { "type": "text", "text": "stable system prompt" },
            { "type": "text", "text": "user definition" }
        ]);
        let messages = vec![json!({"role": "user", "content": "hi"})];
        let (_, sys, p) = apply_cache_control(&messages, &system, "5m", &[], &[0]);

        let blocks = sys.as_array().unwrap();
        assert!(blocks[0].get("cache_control").is_none());
        assert!(blocks[1].get("cache_control").is_some());
        assert_eq!(p.sys_breakpoints, vec![1]);
    }

    #[test]
    fn test_apply_cache_control_pinned_system_second_to_last() {
        // cache_pinned_position = [-1] → second-to-last system block.
        let system = json!([
            { "type": "text", "text": "stable system prompt" },
            { "type": "text", "text": "recap that changes", "_label": "recap" }
        ]);
        let messages = vec![json!({"role": "user", "content": "hi"})];
        let (_, sys, p) = apply_cache_control(&messages, &system, "5m", &[], &[-1]);

        let blocks = sys.as_array().unwrap();
        assert!(blocks[0].get("cache_control").is_some());
        assert!(blocks[1].get("cache_control").is_none());
        assert_eq!(p.sys_breakpoints, vec![0]);
        // _label fields should be stripped.
        assert!(blocks[0].get("_label").is_none());
        assert!(blocks[1].get("_label").is_none());
    }

    #[test]
    fn test_apply_cache_control_single_system_block() {
        // cache_pinned_position = [0] with single block.
        let system = json!([{ "type": "text", "text": "only block" }]);
        let messages = vec![json!({"role": "user", "content": "hi"})];
        let (_, sys, p) = apply_cache_control(&messages, &system, "5m", &[], &[0]);

        let blocks = sys.as_array().unwrap();
        assert!(blocks[0].get("cache_control").is_some());
        assert_eq!(p.sys_breakpoints, vec![0]);
    }

    #[test]
    fn test_apply_cache_control_depth_turns() {
        // cache_depth_turns = [2] → sliding breakpoint 2 user turns back.
        let messages = vec![
            json!({"role": "user", "content": "turn 1"}),
            json!({"role": "assistant", "content": "resp 1"}),
            json!({"role": "user", "content": "turn 2"}),
            json!({"role": "assistant", "content": "resp 2"}),
            json!({"role": "user", "content": "turn 3"}),
            json!({"role": "assistant", "content": "resp 3"}),
            json!({"role": "user", "content": "turn 4"}),
        ];
        let (_, _, p) = apply_cache_control(&messages, &json!(null), "5m", &[2], &[]);

        // depth=2: 2 real user turns back from end → breakpoint before turn 2
        // (the assistant response at index 1).
        assert_eq!(p.msg_breakpoints.len(), 1);
        assert!(p.msg_breakpoints[0] < messages.len());
    }

    #[test]
    fn test_apply_cache_control_normalizes_string_content() {
        let messages = vec![
            json!({"role": "user", "content": "hello"}),
            json!({"role": "assistant", "content": "hi there"}),
        ];
        let (result, _, _) = apply_cache_control(&messages, &json!(null), "5m", &[2], &[]);

        // All string content should be normalized to array format.
        for msg in &result {
            assert!(
                msg["content"].is_array(),
                "content should be normalized to array, got: {}",
                msg["content"]
            );
        }
    }

    #[test]
    fn test_apply_cache_control_custom_ttl() {
        let system = json!([{ "type": "text", "text": "prompt" }]);
        let messages = vec![json!({"role": "user", "content": "hi"})];
        let (_, sys, _) = apply_cache_control(&messages, &system, "10m", &[], &[0]);

        let cc = &sys.as_array().unwrap()[0]["cache_control"];
        assert_eq!(cc["type"], "ephemeral");
        assert_eq!(cc["ttl"], "10m");
    }

    #[test]
    fn test_apply_cache_control_combined_breakpoints() {
        // Both system and message breakpoints. Needs enough turns for
        // depth=1 to resolve past index 0 (which is now filtered out).
        let system = json!([
            { "type": "text", "text": "stable prompt" },
            { "type": "text", "text": "more prompt" }
        ]);
        let messages = vec![
            json!({"role": "user", "content": "turn 1"}),
            json!({"role": "assistant", "content": "resp 1"}),
            json!({"role": "user", "content": "turn 2"}),
            json!({"role": "assistant", "content": "resp 2"}),
            json!({"role": "user", "content": "turn 3"}),
        ];
        let (_, sys, p) = apply_cache_control(&messages, &system, "1h", &[1], &[0]);

        // System breakpoint on last block.
        assert!(sys.as_array().unwrap()[1].get("cache_control").is_some());
        assert_eq!(p.sys_breakpoints, vec![1]);
        // Message breakpoint from depth_turns.
        assert!(!p.msg_breakpoints.is_empty());
    }

    #[test]
    fn test_apply_cache_control_no_breakpoints_configured() {
        // No depth_turns, no pinned_positions → no breakpoints placed.
        let system = json!([{ "type": "text", "text": "prompt" }]);
        let messages = vec![json!({"role": "user", "content": "hi"})];
        let (_, sys, p) = apply_cache_control(&messages, &system, "5m", &[], &[]);

        let blocks = sys.as_array().unwrap();
        assert!(blocks[0].get("cache_control").is_none());
        assert!(p.msg_breakpoints.is_empty());
        assert!(p.sys_breakpoints.is_empty());
    }

    // ── Regression: system anchor required for stable caching ──────────
    //
    // Empirically confirmed: sliding message breakpoints (depth_turns)
    // WITHOUT a pinned system breakpoint cause intermittent full prefix
    // rewrites on the Anthropic API. These tests verify the structural
    // properties that make the working configs work.

    /// Helper: builds a conversation of N turns (user/assistant pairs +
    /// final user message).
    fn build_conversation(turns: usize) -> Vec<Value> {
        let mut msgs = Vec::new();
        for i in 1..=turns {
            msgs.push(json!({"role": "user", "content": format!("turn {i}")}));
            if i < turns {
                msgs.push(json!({"role": "assistant", "content": format!("resp {i}")}));
            }
        }
        msgs
    }

    /// Helper: builds a multi-block system prompt like assemble_prompt
    /// produces (template + char def + memory_index).
    fn build_system_with_memory_index() -> Value {
        json!([
            { "type": "text", "text": "You are TestChar, in conversation with User." },
            { "type": "text", "text": "<testchar>\nA test character.\n</testchar>" },
            { "type": "text", "text": "<memory_index>\nMEMORY.md contents.\n</memory_index>" }
        ])
    }

    fn generated_history(turns: usize, content_variant: usize, tail_kind: usize) -> Vec<Value> {
        let mut msgs = Vec::new();
        for i in 0..turns {
            let user_content = if content_variant % 2 == 0 {
                json!(format!("turn {i} user"))
            } else {
                json!([
                    {"type": "text", "text": format!("turn {i} user prelude")},
                    {"type": "text", "text": format!("turn {i} user")}
                ])
            };
            msgs.push(json!({"role": "user", "content": user_content}));

            let is_last = i + 1 == turns;
            if !is_last || tail_kind == 1 {
                let assistant_content = if content_variant % 2 == 0 {
                    json!(format!("turn {i} assistant"))
                } else {
                    json!([{"type": "text", "text": format!("turn {i} assistant")}])
                };
                msgs.push(json!({"role": "assistant", "content": assistant_content}));
            }

            if is_last && tail_kind >= 2 {
                let tool_count = tail_kind - 1;
                for t in 0..tool_count {
                    msgs.push(json!({"role": "assistant", "content": [
                        {"type": "tool_use", "id": format!("tool-{t}"), "name": "read", "input": {"path": "memory/a.md"}}
                    ]}));
                    msgs.push(json!({"role": "user", "content": [
                        {"type": "tool_result", "tool_use_id": format!("tool-{t}"), "content": format!("result {t}")}
                    ]}));
                }
            }
        }
        msgs
    }

    fn generated_system(blocks: usize) -> Value {
        if blocks == 0 {
            return json!(null);
        }
        let mut sys = Vec::new();
        for i in 0..blocks {
            let text = if i + 1 == blocks {
                format!("<memory_index>\nvolatile index {i}\n</memory_index>")
            } else {
                format!("stable system block {i}")
            };
            sys.push(json!({"type": "text", "text": text, "_label": format!("block-{i}")}));
        }
        Value::Array(sys)
    }

    fn cache_control_count(value: &Value) -> usize {
        match value {
            Value::Array(items) => items.iter().map(cache_control_count).sum(),
            Value::Object(obj) => {
                usize::from(obj.contains_key("cache_control"))
                    + obj.values().map(cache_control_count).sum::<usize>()
            }
            _ => 0,
        }
    }

    fn message_has_cache_control(msg: &Value) -> bool {
        msg.get("content")
            .and_then(Value::as_array)
            .is_some_and(|arr| arr.iter().any(|block| block.get("cache_control").is_some()))
    }

    fn last_real_user_idx(messages: &[Value]) -> Option<usize> {
        messages.iter().rposition(|msg| {
            msg.get("role").and_then(Value::as_str) == Some("user") && !is_tool_result_message(msg)
        })
    }

    #[test]
    fn test_default_sliding_config_system_anchor_present() {
        // Config: depth=[0,1] pinned=[0]. The system anchor must always be
        // present for sliding message breakpoints to work reliably.
        let system = build_system_with_memory_index();
        let msgs = build_conversation(5);
        let (result, sys, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[0]);

        // Must have exactly 1 system breakpoint on the last block (memory_index).
        assert_eq!(
            p.sys_breakpoints,
            vec![2],
            "system bp must be on last block (index 2)"
        );
        let sys_blocks = sys.as_array().unwrap();
        assert!(
            sys_blocks[2].get("cache_control").is_some(),
            "last system block must have cache_control"
        );
        assert!(
            sys_blocks[0].get("cache_control").is_none(),
            "first system block must NOT have cache_control"
        );
        assert!(
            sys_blocks[1].get("cache_control").is_none(),
            "middle system block must NOT have cache_control"
        );

        // Must have exactly 2 message breakpoints.
        assert_eq!(
            p.msg_breakpoints.len(),
            2,
            "expected 2 message breakpoints, got {:?}",
            p.msg_breakpoints
        );

        // Message breakpoints must have cache_control on their last text block.
        for &bp_idx in &p.msg_breakpoints {
            let content = result[bp_idx]["content"]
                .as_array()
                .expect("content should be array");
            let last_text = content
                .iter()
                .rev()
                .find(|b| b.get("type").and_then(Value::as_str) == Some("text"))
                .expect("should have text block");
            assert!(
                last_text.get("cache_control").is_some(),
                "message breakpoint at index {} missing cache_control",
                bp_idx
            );
        }

        // Total breakpoints must not exceed 4.
        assert!(p.sys_breakpoints.len() + p.msg_breakpoints.len() <= 4);
    }

    #[test]
    fn cache_control_property_matrix_accounts_for_generated_histories() {
        let depth_sets: &[&[u32]] = &[&[], &[0], &[0, 1], &[0, 1, 2, 3], &[1, 3]];
        let pin_sets: &[&[i32]] = &[&[], &[0], &[-1], &[-2, 0]];

        for turns in 1..=8 {
            for content_variant in 0..=1 {
                for tail_kind in 0..=3 {
                    let messages = generated_history(turns, content_variant, tail_kind);
                    for system_blocks in 0..=4 {
                        let system = generated_system(system_blocks);
                        for depths in depth_sets {
                            for pins in pin_sets {
                                let (result, sys, placement) =
                                    apply_cache_control(&messages, &system, "1h", depths, pins);
                                let total_breakpoints = placement.sys_breakpoints.len()
                                    + placement.msg_breakpoints.len();

                                assert!(
                                    total_breakpoints <= 4,
                                    "breakpoint limit exceeded: turns={turns}, variant={content_variant}, tail={tail_kind}, sys={system_blocks}, depths={depths:?}, pins={pins:?}, placement={:?}/{:?}",
                                    placement.sys_breakpoints,
                                    placement.msg_breakpoints
                                );
                                assert_eq!(
                                    cache_control_count(&sys)
                                        + result.iter().map(cache_control_count).sum::<usize>(),
                                    total_breakpoints,
                                    "every reported breakpoint should have exactly one cache_control marker"
                                );

                                for (idx, msg) in result.iter().enumerate() {
                                    assert!(
                                        msg.get("content").is_some_and(Value::is_array),
                                        "message content should be normalized to block arrays"
                                    );
                                    assert_eq!(
                                        message_has_cache_control(msg),
                                        placement.msg_breakpoints.contains(&idx),
                                        "message marker accounting mismatch at index {idx}"
                                    );
                                }

                                if messages.last().is_some_and(|msg| {
                                    msg.get("role").and_then(Value::as_str) == Some("user")
                                        && !is_tool_result_message(msg)
                                }) {
                                    let active_idx = last_real_user_idx(&messages).unwrap();
                                    assert!(
                                        !placement.msg_breakpoints.contains(&active_idx),
                                        "active final user message must not become a cache breakpoint"
                                    );
                                }

                                for idx in placement.sys_breakpoints {
                                    assert!(
                                        idx < system_blocks,
                                        "system breakpoint index {idx} must be inside {system_blocks} blocks"
                                    );
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn test_pinned_neg1_with_memory_index_targets_char_def() {
        // Config: depth=[0,1] pinned=[-1] — current default config.
        // With 3 system blocks (template, char def, memory_index), -1 should
        // target index 1 (char def), NOT the memory_index.
        let system = build_system_with_memory_index();
        let msgs = build_conversation(5);
        let (_, sys, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[-1]);

        assert_eq!(
            p.sys_breakpoints,
            vec![1],
            "pinned=[-1] with 3 blocks must target index 1 (char def)"
        );
        let sys_blocks = sys.as_array().unwrap();
        assert!(
            sys_blocks[1].get("cache_control").is_some(),
            "char def block must have cache_control"
        );
        assert!(
            sys_blocks[2].get("cache_control").is_none(),
            "memory_index block must NOT have cache_control (it changes)"
        );
    }

    #[test]
    fn test_sliding_breakpoints_stable_across_growing_conversation() {
        // The critical property: as the conversation grows, the PREFIX
        // content before the earliest breakpoint must remain identical
        // (same bytes, same structure). If the prefix changes, the cache
        // is busted.
        let system = build_system_with_memory_index();
        let mut prev_sys_hash: Option<String> = None;

        for turn_count in 4..=10 {
            let msgs = build_conversation(turn_count);
            let (result, sys, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[0]);

            // System must be structurally identical every turn.
            let sys_str = sys.to_string();
            if let Some(prev) = &prev_sys_hash {
                assert_eq!(
                    &sys_str,
                    prev,
                    "system payload changed between turn {} and {}",
                    turn_count - 1,
                    turn_count
                );
            }
            prev_sys_hash = Some(sys_str);

            // The prefix (everything up to the earliest message breakpoint)
            // must be stable and growing. Content before the breakpoint
            // should only grow by appended messages, never change existing.
            if let Some(&earliest_bp) = p.msg_breakpoints.first() {
                // Verify no cache_control leaked onto non-breakpoint messages
                // in the prefix (would change the serialized form).
                for (i, msg) in result[..earliest_bp].iter().enumerate() {
                    if !p.msg_breakpoints.contains(&i) {
                        let has_cc = msg["content"]
                            .as_array()
                            .map(|arr| arr.iter().any(|b| b.get("cache_control").is_some()))
                            .unwrap_or(false);
                        assert!(
                            !has_cc,
                            "turn {}: non-breakpoint message {} in prefix has cache_control",
                            turn_count, i
                        );
                    }
                }

                if turn_count > 5 {
                    assert!(
                        earliest_bp >= 2,
                        "turn {}: earliest breakpoint {} is too close to start",
                        turn_count,
                        earliest_bp
                    );
                }
            }
        }
    }

    #[test]
    fn test_depth_breakpoints_move_predictably() {
        // Verify that as we add messages, the breakpoint indices shift
        // by exactly 2 per turn (one user + one assistant message added).
        let system = json!([{ "type": "text", "text": "prompt" }]);
        let mut prev_bp: Option<Vec<usize>> = None;

        for turn_count in 4..=8 {
            let msgs = build_conversation(turn_count);
            let (_, _, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[0]);

            if let Some(prev) = &prev_bp {
                // Each new turn adds 2 messages (assistant + user), so
                // each breakpoint should shift by exactly 2.
                assert_eq!(
                    p.msg_breakpoints.len(),
                    prev.len(),
                    "breakpoint count changed between turn {} and {}",
                    turn_count - 1,
                    turn_count
                );
                for (i, (&cur, &prv)) in p.msg_breakpoints.iter().zip(prev.iter()).enumerate() {
                    assert_eq!(
                        cur,
                        prv + 2,
                        "breakpoint {} shifted by {} (expected 2) between turn {} and {}",
                        i,
                        cur as i64 - prv as i64,
                        turn_count - 1,
                        turn_count
                    );
                }
            }
            prev_bp = Some(p.msg_breakpoints.clone());
        }
    }

    #[test]
    fn test_breakpoint_content_not_on_final_user_message() {
        // A breakpoint on the final user message means the ENTIRE
        // conversation is in the cached prefix, which defeats the purpose
        // (nothing would ever be un-cached for the response). Verify that
        // no message breakpoint lands on the last message.
        let system = build_system_with_memory_index();
        for turn_count in 1..=10 {
            let msgs = build_conversation(turn_count);
            let last_idx = msgs.len() - 1;
            let (_, _, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[0]);
            for &bp in &p.msg_breakpoints {
                assert_ne!(
                    bp, last_idx,
                    "turn {}: breakpoint at index {} is the final message",
                    turn_count, bp
                );
            }
        }
    }

    #[test]
    fn test_default_depths_single_user_has_no_message_breakpoint() {
        let system = build_system_with_memory_index();
        let msgs = build_conversation(1);
        let (_, _, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1], &[-1]);

        assert!(
            p.msg_breakpoints.is_empty(),
            "single active user message must not be cached as a message breakpoint"
        );
        assert_eq!(p.sys_breakpoints, vec![1]);
    }

    #[test]
    fn test_tool_loop_depths_target_recent_tool_results() {
        let system = build_system_with_memory_index();
        let messages = vec![
            json!({"role": "user", "content": "please inspect memory"}),
            json!({"role": "assistant", "content": [
                {"type": "tool_use", "id": "t1", "name": "read", "input": {"path": "memory/a.md"}}
            ]}),
            json!({"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "first result"}
            ]}),
            json!({"role": "assistant", "content": [
                {"type": "tool_use", "id": "t2", "name": "read", "input": {"path": "memory/b.md"}}
            ]}),
            json!({"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t2", "content": "second result"}
            ]}),
        ];

        let (result, _, p) = apply_cache_control(&messages, &system, "1h", &[0, 1], &[-1]);

        assert_eq!(
            p.msg_breakpoints,
            vec![2, 4],
            "active tool-loop breakpoints should advance through completed tool results"
        );
        for idx in p.msg_breakpoints {
            let blocks = result[idx]["content"].as_array().unwrap();
            let tool_result = blocks
                .iter()
                .find(|b| b.get("type").and_then(Value::as_str) == Some("tool_result"))
                .expect("breakpoint should land on a tool_result block");
            assert!(
                tool_result.get("cache_control").is_some(),
                "tool_result at message {idx} should carry cache_control"
            );
        }
    }

    #[test]
    fn test_four_breakpoint_limit_enforced() {
        // With pinned=[0] (1 sys bp) and depth=[0,1,2,3] (4 msg bp),
        // total would be 5 — must be truncated to 4.
        let system = json!([
            { "type": "text", "text": "block 1" },
            { "type": "text", "text": "block 2" }
        ]);
        let msgs = build_conversation(8);
        let (_, _, p) = apply_cache_control(&msgs, &system, "1h", &[0, 1, 2, 3], &[0]);
        let total = p.sys_breakpoints.len() + p.msg_breakpoints.len();
        assert!(
            total <= 4,
            "total breakpoints {} exceeds Anthropic limit of 4",
            total
        );
        // System breakpoints should be preserved (priority).
        assert_eq!(
            p.sys_breakpoints.len(),
            1,
            "system breakpoint should be preserved when truncating"
        );
    }

    // ── convert_inline_system_messages ─────────────────────────────────

    #[test]
    fn test_convert_inline_system_no_system_messages() {
        let messages = vec![
            json!({"role": "user", "content": "hello"}),
            json!({"role": "assistant", "content": "hi"}),
        ];
        let result = convert_inline_system_messages(&messages);
        assert_eq!(result.len(), 2);
        assert_eq!(result[0]["role"], "user");
        assert_eq!(result[1]["role"], "assistant");
    }

    #[test]
    fn test_convert_inline_system_standalone() {
        let messages = vec![
            json!({"role": "assistant", "content": "prev response"}),
            json!({"role": "system", "content": "be helpful"}),
            json!({"role": "user", "content": "hello"}),
        ];
        let result = convert_inline_system_messages(&messages);

        // system becomes a user message with XML wrapper; no synthetic ack.
        assert_eq!(result.len(), 3);
        assert_eq!(result[0]["role"], "assistant");
        assert_eq!(result[1]["role"], "user");
        assert!(result[1]["content"]
            .as_str()
            .unwrap()
            .contains("<system_instruction>"));
        assert!(result[1]["content"]
            .as_str()
            .unwrap()
            .contains("be helpful"));
        assert_eq!(result[2]["role"], "user");
    }

    #[test]
    fn test_convert_inline_system_merges_into_preceding_user() {
        let messages = vec![
            json!({"role": "user", "content": "hello"}),
            json!({"role": "system", "content": "be concise"}),
        ];
        let result = convert_inline_system_messages(&messages);

        // System merged into preceding user message to avoid consecutive user roles.
        assert_eq!(result.len(), 1);
        assert_eq!(result[0]["role"], "user");
        let content = result[0]["content"].as_str().unwrap();
        assert!(content.contains("hello"));
        assert!(content.contains("<system_instruction>be concise</system_instruction>"));
    }

    /// Regression: when a system message lands after a user message whose
    /// content is a structured array (e.g. tool_result blocks from a tool
    /// loop), the merge must preserve those blocks. Previously
    /// `extract_text_content` stringified the content and silently dropped
    /// non-text blocks, breaking tool_use/tool_result pairing.
    #[test]
    fn test_convert_inline_system_preserves_structured_prev_content() {
        let messages = vec![
            json!({"role": "assistant", "content": [
                {"type": "tool_use", "id": "t1", "name": "memory_search", "input": {"query": "Ren"}},
            ]}),
            json!({"role": "user", "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "ok"},
            ]}),
            json!({"role": "system", "content": "wrap up now"}),
        ];
        let result = convert_inline_system_messages(&messages);

        assert_eq!(result.len(), 2, "system merges into preceding user turn");
        assert_eq!(result[1]["role"], "user");
        let blocks = result[1]["content"]
            .as_array()
            .expect("content must remain an array so tool_result is preserved");
        assert_eq!(blocks.len(), 2, "tool_result + appended text block");
        assert_eq!(blocks[0]["type"], "tool_result");
        assert_eq!(blocks[0]["tool_use_id"], "t1");
        assert_eq!(blocks[1]["type"], "text");
        assert!(blocks[1]["text"]
            .as_str()
            .unwrap()
            .contains("<system_instruction>wrap up now</system_instruction>"));
    }

    /// Regression: trailing system message (the heartbeat case) must
    /// produce a final *user* turn so the model generates a fresh response.
    /// Previously a synthetic `assistant: "Understood."` was appended,
    /// creating an unintentional prefill that caused verbatim-identical
    /// output across heartbeat ticks.
    #[test]
    fn test_trailing_system_message_no_prefill() {
        // Simulates the heartbeat tick: conversation ends with assistant,
        // then a system message is appended as the final message.
        let messages = vec![
            json!({"role": "user", "content": "How are you?"}),
            json!({"role": "assistant", "content": "Doing well, thanks!"}),
            json!({"role": "system", "content": "This is your private moment. Reflect freely."}),
        ];
        let result = convert_inline_system_messages(&messages);

        assert_eq!(result.len(), 3);
        assert_eq!(result[0]["role"], "user");
        assert_eq!(result[1]["role"], "assistant");
        // Final message must be user — the model generates from here.
        assert_eq!(result[2]["role"], "user");
        assert!(result[2]["content"]
            .as_str()
            .unwrap()
            .contains("<system_instruction>"));
        assert!(result[2]["content"]
            .as_str()
            .unwrap()
            .contains("Reflect freely."));
        // No "Understood." anywhere — it would create a prefill.
        for msg in &result {
            assert_ne!(
                msg["content"], "Understood.",
                "synthetic ack must not appear — it creates an unintentional prefill"
            );
        }
    }

    // ── build_thinking_config ─────────────────────────────────────────

    #[test]
    fn test_build_thinking_config_adaptive() {
        let opts = json!({"reasoning_effort": "adaptive"});
        let config = build_thinking_config(&opts).unwrap();
        assert_eq!(config["type"], "adaptive");
    }

    #[test]
    fn test_build_thinking_config_budget() {
        let opts = json!({"thinking": true, "budget_tokens": 2048});
        let config = build_thinking_config(&opts).unwrap();
        assert_eq!(config["type"], "enabled");
        assert_eq!(config["budget_tokens"], 2048);
    }

    #[test]
    fn test_build_thinking_config_none() {
        let opts = json!({});
        assert!(build_thinking_config(&opts).is_none());
    }

    // ── build_body ────────────────────────────────────────────────────

    #[test]
    fn test_build_body_minimal() {
        let request = make_request(vec![json!({"role": "user", "content": "hi"})], None);
        let (body, _) = build_body(&request, false);

        assert_eq!(body["model"], "claude-test");
        assert_eq!(body["max_tokens"], 4096);
        assert!(body["messages"].is_array());
        assert!(body.get("stream").is_none());
    }

    #[test]
    fn test_build_body_with_tools_and_system() {
        let mut request = make_request(
            vec![json!({"role": "user", "content": "search for cats"})],
            Some(json!("You are helpful.")),
        );
        request.tools = Some(vec![json!({
            "name": "web_search",
            "description": "Search the web",
            "input_schema": {"type": "object"}
        })]);
        let (body, _) = build_body(&request, false);

        assert!(body.get("system").is_some());
        assert!(body["tools"].is_array());
        assert_eq!(body["tools"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn test_build_body_streaming_flag() {
        let request = make_request(vec![json!({"role": "user", "content": "hi"})], None);
        let (body, _) = build_body(&request, true);
        assert_eq!(body["stream"], true);

        let (body_no_stream, _) = build_body(&request, false);
        assert!(body_no_stream.get("stream").is_none());
    }

    // ── SSE event handlers ────────────────────────────────────────────

    #[test]
    fn test_handle_sse_event_message_start() {
        let data = json!({
            "type": "message_start",
            "message": {
                "model": "claude-3-opus-20240229",
                "usage": {"input_tokens": 100}
            }
        })
        .to_string();

        let mut state = StreamState::new("unknown");
        let result = handle_message_start(&data, &mut state);

        assert!(result.is_some());
        let event: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(event["type"], "start");
        assert_eq!(event["model"], "claude-3-opus-20240229");
        assert_eq!(state.model, "claude-3-opus-20240229");
        assert_eq!(state.usage.input_tokens, 100);
    }

    #[test]
    fn test_handle_sse_event_tool_use_lifecycle() {
        let mut state = StreamState::new("claude-test");

        // 1. content_block_start: register tool block.
        let start_data = json!({
            "index": 0,
            "content_block": {
                "type": "tool_use",
                "id": "toolu_123",
                "name": "web_search"
            }
        })
        .to_string();
        let r1 = handle_content_block_start(&start_data, &mut state);
        assert!(r1.is_none(), "content_block_start should not emit");
        assert!(state.tool_blocks.contains_key(&0));

        // 2. content_block_delta: accumulate JSON.
        let delta_data = json!({
            "index": 0,
            "delta": {
                "type": "input_json_delta",
                "partial_json": "{\"query\":"
            }
        })
        .to_string();
        let r2 = handle_content_block_delta(&delta_data, &mut state);
        assert!(r2.is_none(), "input_json_delta should not emit");

        let delta_data2 = json!({
            "index": 0,
            "delta": {
                "type": "input_json_delta",
                "partial_json": "\"cats\"}"
            }
        })
        .to_string();
        handle_content_block_delta(&delta_data2, &mut state);

        // 3. content_block_stop: emit tool_use event.
        let stop_data = json!({"index": 0}).to_string();
        let r3 = handle_content_block_stop(&stop_data, &mut state);
        assert!(r3.is_some());
        let event: Value = serde_json::from_str(&r3.unwrap()).unwrap();
        assert_eq!(event["type"], "tool_use");
        assert_eq!(event["id"], "toolu_123");
        assert_eq!(event["name"], "web_search");
        assert_eq!(event["input"]["query"], "cats");
    }

    // ── handle_sse_event dispatch ────────────────────────────────────

    #[test]
    fn test_handle_sse_event_unknown_type_returns_none() {
        let mut state = StreamState::new("claude-test");
        let event = SseEvent {
            event: Some("totally_unknown".into()),
            data: "{}".into(),
        };
        assert!(handle_sse_event(event, &mut state).is_none());
    }

    #[test]
    fn test_handle_sse_event_ping_returns_none() {
        let mut state = StreamState::new("claude-test");
        let event = SseEvent {
            event: Some("ping".into()),
            data: "{}".into(),
        };
        assert!(handle_sse_event(event, &mut state).is_none());
    }

    #[test]
    fn test_handle_sse_event_falls_back_to_json_type_field() {
        // OpenRouter proxy case: no event: field, type inside data payload.
        let mut state = StreamState::new("claude-test");
        let data = json!({
            "type": "message_start",
            "message": {
                "model": "claude-proxy",
                "usage": {"input_tokens": 50}
            }
        })
        .to_string();
        let event = SseEvent { event: None, data };
        let result = handle_sse_event(event, &mut state);
        assert!(result.is_some());
        let parsed: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(parsed["type"], "start");
        assert_eq!(state.model, "claude-proxy");
    }

    // ── handle_content_block_delta ───────────────────────────────────

    #[test]
    fn test_text_delta_emits_and_accumulates() {
        let mut state = StreamState::new("claude-test");
        assert!(state.first_token_time.is_none());

        let data = json!({
            "index": 0,
            "delta": { "type": "text_delta", "text": "Hello " }
        })
        .to_string();
        let result = handle_content_block_delta(&data, &mut state);

        assert!(result.is_some());
        let event: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(event["type"], "text");
        assert_eq!(event["text"], "Hello ");
        assert_eq!(state.text_content, "Hello ");
        assert!(state.first_token_time.is_some());

        // Second delta accumulates.
        let data2 = json!({
            "index": 0,
            "delta": { "type": "text_delta", "text": "world" }
        })
        .to_string();
        handle_content_block_delta(&data2, &mut state);
        assert_eq!(state.text_content, "Hello world");
    }

    #[test]
    fn test_thinking_delta_emits() {
        let mut state = StreamState::new("claude-test");
        state.thinking_blocks.insert(0);

        let data = json!({
            "index": 0,
            "delta": { "type": "thinking_delta", "thinking": "Let me consider..." }
        })
        .to_string();
        let result = handle_content_block_delta(&data, &mut state);

        assert!(result.is_some());
        let event: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(event["type"], "thinking");
        assert_eq!(event["text"], "Let me consider...");
        assert!(state.first_token_time.is_some());
    }

    #[test]
    fn test_signature_delta_accumulates_without_emitting() {
        let mut state = StreamState::new("claude-test");
        state.thinking_blocks.insert(0);

        let data = json!({
            "index": 0,
            "delta": { "type": "signature_delta", "signature": "sig_part1" }
        })
        .to_string();
        let result = handle_content_block_delta(&data, &mut state);
        assert!(result.is_none());
        assert_eq!(state.thinking_signatures.get(&0).unwrap(), "sig_part1");

        // Second chunk appends.
        let data2 = json!({
            "index": 0,
            "delta": { "type": "signature_delta", "signature": "_part2" }
        })
        .to_string();
        handle_content_block_delta(&data2, &mut state);
        assert_eq!(
            state.thinking_signatures.get(&0).unwrap(),
            "sig_part1_part2"
        );
    }

    // ── handle_content_block_start ───────────────────────────────────

    #[test]
    fn test_content_block_start_redacted_thinking() {
        let mut state = StreamState::new("claude-test");
        let data = json!({
            "index": 0,
            "content_block": { "type": "redacted_thinking", "data": "encrypted_blob" }
        })
        .to_string();

        let result = handle_content_block_start(&data, &mut state);
        assert!(result.is_none());
        assert_eq!(
            state.redacted_thinking_blocks.get(&0).unwrap(),
            "encrypted_blob"
        );
    }

    #[test]
    fn test_content_block_start_openrouter_redacted_filtered() {
        let mut state = StreamState::new("claude-test");
        let data = json!({
            "index": 0,
            "content_block": {
                "type": "redacted_thinking",
                "data": "openrouter.reasoning: some duplicate content"
            }
        })
        .to_string();

        let result = handle_content_block_start(&data, &mut state);
        assert!(result.is_none());
        assert!(
            state.redacted_thinking_blocks.is_empty(),
            "OpenRouter bogus redacted_thinking should be filtered"
        );
    }

    // ── handle_content_block_stop ────────────────────────────────────

    #[test]
    fn test_content_block_stop_thinking_emits_signature() {
        let mut state = StreamState::new("claude-test");
        state.thinking_blocks.insert(0);
        state.thinking_signatures.insert(0, "sig_complete".into());

        let data = json!({"index": 0}).to_string();
        let result = handle_content_block_stop(&data, &mut state);

        assert!(result.is_some());
        let event: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(event["type"], "thinking_signature");
        assert_eq!(event["signature"], "sig_complete");
        assert!(!state.thinking_blocks.contains(&0));
        assert!(!state.thinking_signatures.contains_key(&0));
    }

    #[test]
    fn test_content_block_stop_redacted_thinking_emits() {
        let mut state = StreamState::new("claude-test");
        state
            .redacted_thinking_blocks
            .insert(0, "opaque_data".into());

        let data = json!({"index": 0}).to_string();
        let result = handle_content_block_stop(&data, &mut state);

        assert!(result.is_some());
        let event: Value = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(event["type"], "redacted_thinking");
        assert_eq!(event["data"], "opaque_data");
        assert!(!state.redacted_thinking_blocks.contains_key(&0));
    }

    // ── handle_message_delta ─────────────────────────────────────────

    #[test]
    fn test_message_delta_sets_finish_reason_and_usage() {
        let mut state = StreamState::new("claude-test");
        let data = json!({
            "delta": { "stop_reason": "tool_use" },
            "usage": { "output_tokens": 42 }
        })
        .to_string();

        handle_message_delta(&data, &mut state);
        assert_eq!(state.finish_reason, "tool_use");
        assert_eq!(state.usage.output_tokens, 42);
    }

    // ── handle_message_stop ──────────────────────────────────────────

    #[test]
    fn test_message_stop_produces_done_event() {
        let mut state = StreamState::new("claude-test");
        state.text_content = "Final answer.".into();
        state.finish_reason = "end_turn".into();
        state.usage.input_tokens = 100;
        state.usage.output_tokens = 50;

        let result = handle_message_stop(&mut state);
        let event: Value = serde_json::from_str(&result).unwrap();

        assert_eq!(event["type"], "done");
        assert_eq!(event["content"], "Final answer.");
        assert_eq!(event["finish_reason"], "end_turn");
        assert_eq!(event["usage"]["input_tokens"], 100);
        assert_eq!(event["usage"]["output_tokens"], 50);
        // Timing fields exist but values are non-deterministic.
        assert!(event.get("timing").is_some());
    }

    // ── is_tool_result_message ──────────────────────────────────────

    #[test]
    fn test_is_tool_result_user_with_tool_results() {
        let msg = json!({
            "role": "user",
            "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "ok"}
            ]
        });
        assert!(is_tool_result_message(&msg));
    }

    #[test]
    fn test_is_tool_result_user_with_text() {
        let msg = json!({"role": "user", "content": "hello"});
        assert!(!is_tool_result_message(&msg));
    }

    #[test]
    fn test_is_tool_result_assistant_message() {
        let msg = json!({
            "role": "assistant",
            "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "ok"}
            ]
        });
        assert!(!is_tool_result_message(&msg));
    }

    #[test]
    fn test_is_tool_result_mixed_blocks() {
        let msg = json!({
            "role": "user",
            "content": [
                {"type": "tool_result", "tool_use_id": "t1", "content": "ok"},
                {"type": "text", "text": "also some text"}
            ]
        });
        assert!(!is_tool_result_message(&msg));
    }

    #[test]
    fn test_is_tool_result_empty_content_array() {
        let msg = json!({"role": "user", "content": []});
        assert!(!is_tool_result_message(&msg));
    }

    // ── find_turn_boundary ──────────────────────────────────────────

    #[test]
    fn test_find_turn_boundary_empty_messages() {
        assert_eq!(find_turn_boundary(&[], 2), None);
    }

    #[test]
    fn test_find_turn_boundary_single_user_message() {
        let msgs = vec![json!({"role": "user", "content": "hi"})];
        // Never place a breakpoint on the active final user message.
        assert_eq!(find_turn_boundary(&msgs, 0), None);
        assert_eq!(find_turn_boundary(&msgs, 1), None);
        assert_eq!(find_turn_boundary(&msgs, 2), None);
    }

    #[test]
    fn test_find_turn_boundary_depth_zero_uses_previous_message() {
        let msgs = vec![
            json!({"role": "user", "content": "q1"}),
            json!({"role": "assistant", "content": "a1"}),
            json!({"role": "user", "content": "q2"}),
        ];
        assert_eq!(find_turn_boundary(&msgs, 0), Some(1));
        assert_eq!(find_turn_boundary(&msgs, 1), Some(0));
    }

    #[test]
    fn test_find_turn_boundary_skips_tool_result_messages() {
        // Tool-result-only user messages should not count as "real" user turns.
        let msgs = vec![
            json!({"role": "user", "content": "first question"}),
            json!({"role": "assistant", "content": [{"type": "tool_use", "id": "t1", "name": "search", "input": {}}]}),
            json!({"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "result"}]}),
            json!({"role": "assistant", "content": "answer 1"}),
            json!({"role": "user", "content": "second question"}),
            json!({"role": "assistant", "content": "answer 2"}),
            json!({"role": "user", "content": "third question"}),
            json!({"role": "assistant", "content": "answer 3"}),
        ];
        // depth=1: skip current turn, then 1 more → breakpoint before "second question" (index 4)
        // That means the boundary is at index 3 (last message of the turn before).
        let result = find_turn_boundary(&msgs, 1);
        assert_eq!(result, Some(3));
    }

    #[test]
    fn test_find_turn_boundary_exact_depth() {
        let msgs = vec![
            json!({"role": "user", "content": "q1"}),
            json!({"role": "assistant", "content": "a1"}),
            json!({"role": "user", "content": "q2"}),
            json!({"role": "assistant", "content": "a2"}),
            json!({"role": "user", "content": "q3"}),
            json!({"role": "assistant", "content": "a3"}),
        ];
        // depth=2: skip current turn (q3), then count 2 real user messages back.
        // That's q2 (1) and q1 (2). depth+1=3 matches q1 at index 0.
        // i=0 so i > 0 is false for exact match — falls back to index 0.
        assert_eq!(find_turn_boundary(&msgs, 2), Some(0));

        // depth=1: skip q3, count 1 back → q2 at index 2, return i-1=1.
        assert_eq!(find_turn_boundary(&msgs, 1), Some(1));
    }

    #[test]
    fn test_find_turn_boundary_only_tool_result_users() {
        let msgs = vec![
            json!({"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "r1"}]}),
            json!({"role": "assistant", "content": "a1"}),
            json!({"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t2", "content": "r2"}]}),
            json!({"role": "assistant", "content": "a2"}),
        ];
        // No real user messages → None.
        assert_eq!(find_turn_boundary(&msgs, 1), None);
    }

    // ── base_url acceptance ───────────────────────────────────────────

    #[test]
    fn build_http_request_accepts_custom_base_url() {
        let client = reqwest::Client::new();
        let mut request = make_request(vec![json!({"role": "user", "content": "hi"})], None);
        request.base_url = Some("https://openrouter.ai/api".into());

        // Should NOT return an error — custom base_url is now accepted.
        let result = build_http_request(&client, &request, false);
        assert!(result.is_ok(), "custom base_url should be accepted");

        let (builder, _) = result.unwrap();
        let built = builder.build().unwrap();
        assert_eq!(
            built.url().as_str(),
            "https://openrouter.ai/api/v1/messages"
        );
    }

    #[test]
    fn build_http_request_uses_default_base_url() {
        let client = reqwest::Client::new();
        let request = make_request(vec![json!({"role": "user", "content": "hi"})], None);

        let result = build_http_request(&client, &request, false);
        assert!(result.is_ok());

        let (builder, _) = result.unwrap();
        let built = builder.build().unwrap();
        assert_eq!(
            built.url().as_str(),
            "https://api.anthropic.com/v1/messages"
        );
    }

    #[test]
    fn build_http_request_base_url_with_v1_suffix() {
        let client = reqwest::Client::new();
        let mut request = make_request(vec![json!({"role": "user", "content": "hi"})], None);
        // OpenRouter's default base_url ends with /v1 — should not double it.
        request.base_url = Some("https://openrouter.ai/api/v1".into());

        let result = build_http_request(&client, &request, false);
        assert!(result.is_ok());

        let (builder, _) = result.unwrap();
        let built = builder.build().unwrap();
        assert_eq!(
            built.url().as_str(),
            "https://openrouter.ai/api/v1/messages"
        );
    }

    #[test]
    fn build_http_request_localhost_still_works() {
        let client = reqwest::Client::new();
        let mut request = make_request(vec![json!({"role": "user", "content": "hi"})], None);
        request.base_url = Some("http://127.0.0.1:8080".into());

        let result = build_http_request(&client, &request, false);
        assert!(result.is_ok());

        let (builder, _) = result.unwrap();
        let built = builder.build().unwrap();
        assert_eq!(built.url().as_str(), "http://127.0.0.1:8080/v1/messages");
    }

    // ── compaction-tail breakpoint regression ─────────────────────────
    //
    // These tests pin the on-the-wire invariants that the daemon's
    // cached-compaction path relies on. The "compaction tail" shape
    // (1 user prompt appended + `system_suffix`) is defined in
    // shore-daemon's `compaction_impls::COMPACTION_TAIL_USER_PROMPT_COUNT`;
    // changing either should require updating the other in lockstep.

    /// After `convert_inline_system_messages`, a request shaped like a
    /// compaction tail (`[...chat prefix..., user "compact now", system
    /// "compaction system"]`) must merge the trailing system into the
    /// compact-now user, NOT into any earlier prefix user. This is what
    /// makes the cache_control markers placed by chat on the prefix
    /// survive the compaction call verbatim.
    #[test]
    fn compaction_tail_merges_into_compact_now_not_prefix() {
        // Simulate chat-warmed cache: cache_control on prefix user/assistant.
        let cc = json!({"type": "ephemeral"});
        let messages = vec![
            json!({"role": "user", "content": [
                {"type": "text", "text": "prefix u0", "cache_control": cc},
            ]}),
            json!({"role": "assistant", "content": [
                {"type": "text", "text": "prefix a0", "cache_control": cc},
            ]}),
            // Compaction tail: one user prompt + (after preprocess_request)
            // a trailing system block.
            json!({"role": "user", "content": "compact now"}),
            json!({"role": "system", "content": "compaction system"}),
        ];

        let result = convert_inline_system_messages(&messages);

        assert_eq!(
            result.len(),
            3,
            "trailing system must merge into compact-now user, leaving 3 messages"
        );
        // Prefix markers survived on their original messages.
        let u0_blocks = result[0]["content"].as_array().expect("prefix u0 array");
        assert!(
            u0_blocks[0].get("cache_control").is_some(),
            "prefix user cache_control marker must survive — compaction call \
             reuses the chat-warmed cache prefix"
        );
        let a0_blocks = result[1]["content"].as_array().expect("prefix a0 array");
        assert!(
            a0_blocks[0].get("cache_control").is_some(),
            "prefix assistant cache_control marker must survive"
        );
        // The merged compact-now user carries the system instruction.
        assert_eq!(result[2]["role"], "user");
        let merged_content = result[2]["content"].as_str().unwrap_or_default();
        assert!(
            merged_content.contains("compact now"),
            "merge target must be the compact-now user, not a prefix turn"
        );
        assert!(
            merged_content.contains("<system_instruction>compaction system</system_instruction>"),
            "compaction system prompt must be wrapped and merged into compact-now"
        );
    }

    /// When `has_existing_markers` is true (the cached-compaction path),
    /// `apply_cache_control` is skipped and the prefix markers pass
    /// through unchanged. This pins that `build_body` does not strip,
    /// rewrite, or shift those markers — even after the trailing-system
    /// merge changes the message count.
    #[test]
    fn compaction_tail_preserves_cache_breakpoint_positions() {
        let cc = json!({"type": "ephemeral", "ttl": "1h"});
        let mut request = make_request(
            vec![
                json!({"role": "user", "content": [
                    {"type": "text", "text": "prefix u0", "cache_control": cc},
                ]}),
                json!({"role": "assistant", "content": "prefix a0"}),
                json!({"role": "user", "content": [
                    {"type": "text", "text": "prefix u1", "cache_control": cc},
                ]}),
                // Compaction tail (after `preprocess_request` expanded the
                // `system_suffix` into a trailing system block).
                json!({"role": "user", "content": "compact now"}),
                json!({"role": "system", "content": "compaction system"}),
            ],
            Some(json!("chat system")),
        );
        request.provider_options = Some(json!({"cache_ttl": "1h"}));

        let (body, _) = build_body(&request, false);

        let out_messages = body["messages"].as_array().expect("messages array");
        // Trailing system merged into compact-now ⇒ 4 wire messages.
        assert_eq!(
            out_messages.len(),
            4,
            "compaction tail collapses trailing system into compact-now user"
        );
        // Prefix breakpoints stayed on their original messages — chat's
        // cache prefix is reused byte-for-byte.
        let u0_blocks = out_messages[0]["content"]
            .as_array()
            .expect("u0 stays as array");
        assert!(
            u0_blocks[0].get("cache_control").is_some(),
            "prefix u0 cache_control marker preserved"
        );
        let u1_blocks = out_messages[2]["content"]
            .as_array()
            .expect("u1 stays as array");
        assert!(
            u1_blocks[0].get("cache_control").is_some(),
            "prefix u1 cache_control marker preserved"
        );
        // The compact-now turn is now a merged user; it must NOT have
        // gained a cache_control marker (the existing-markers path skips
        // `apply_cache_control`, so no new breakpoints land on the tail).
        let tail = &out_messages[3];
        assert_eq!(tail["role"], "user");
        match &tail["content"] {
            Value::Array(blocks) => {
                for block in blocks {
                    assert!(
                        block.get("cache_control").is_none(),
                        "compaction tail must not gain a fresh cache_control marker"
                    );
                }
            }
            Value::String(s) => {
                assert!(
                    s.contains("<system_instruction>compaction system</system_instruction>"),
                    "compaction system instruction must ride on the merged tail"
                );
            }
            other => panic!("unexpected tail content shape: {other:?}"),
        }
    }
}
