name: Build and publish Arch packages

on:
  push:
    tags: ['v*']

jobs:
  publish:
    uses: mythofmeat/repo-arch/.github/workflows/publish-arch-rust.yml@main
    with:
      pkgbuild_dir: contrib
      extra_pacman_packages: "alsa-lib protobuf"
    secrets:
      REPO_ARCH_TOKEN: ${{ secrets.REPO_ARCH_TOKEN }}
